version: "3.5"
services:
  middleware:
    build:
      context: ./middleware/
      dockerfile: $PWD/Docker/dev.middleware.Dockerfile
    links:
      - mongo
  angular:
    build:
      context: ./frontend/
      dockerfile: $PWD/Docker/dev.frontend.Dockerfile
    volumes:
      - "./frontend/:/app"
      - "/app/node_modules"
  mongo:
    build:
      context: ./database/
      dockerfile: $PWD/Docker/database.Dockerfile
    ports:
      - 27017:27017
    volumes:
      - ./database/storage:/data/db
  nginx:
    build:
      context: ./proxy/
      dockerfile: $PWD/Docker/proxy.Dockerfile
    ports:
      - 5000:80
    links:
      - middleware
      - angular
