version: '3.5'
services:
  # storage of the app
  mongodb:
    tty: true
    image: mongo:latest
  # mongo container to seed the database, not needed after that
  mongo-seed:
    build:
      context: ./database
      dockerfile: seeding.Dockerfile
    links:
      - mongodb
  # sapper app
  app:
    tty: true
    build:
      context: ./app
      dockerfile: docker/prod.Dockerfile
    ports:
      - 80:3000
    links:
      - mongodb
